export const politicalTerms = [
  "election",
  "vote",
  "senate",
  "congress",
  "parliament",
  "democrat",
  "republican",
  "liberal",
  "conservative",
  "campaign",
  "policy",
  "politics",
  "government",
  "prime minister",
  "president",
  "mayor",
  "governor",
  "white house",
  "supreme court",
  "legislation",
  "bill",
  "referendum"
];
